spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:Account
    username: system
    password: hr
    driver-class-name: oracle.jdbc.driver.OracleDriver

server:
  port: ${port}
eureka:
  client:
    service-url:
      defaultZone: ${eureka_url}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
