spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:Account
    username: system
    password: hr
    driver-class-name: oracle.jdbc.driver.OracleDriver
  cloud:
    bus:
      enabled: true
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
server:
  port: ${port}
eureka:
  client:
    service-url:
      defaultZone: ${eureka_url}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
