spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  cloud:
    bus:
      enabled: true
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
  kafka:
    consumer:
      group-id: kyc-service-group
server:
  port: ${port}
eureka:
  client:
    service-url:
      defaultZone: ${eureka_url}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
